name: Deploy Laravel Code (Full First Upload)

on:
  workflow_dispatch:   # run manually from Actions tab
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to get full tags

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "🔖 Deploying version: $VERSION"

      - name: Write version to file
        run: echo "${{ env.version }}" > version.txt

      - name: Deploy all files via FTP (first full deploy)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /      # since your FTP root is already /amigos
          security: loose
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            vendor/**
            tests/**
            storage/framework/cache/**
            storage/framework/sessions/**
            storage/framework/views/**
            storage/logs/**
            storage/debugbar/**
            .env
            .env.*
            .gitattributes
            .gitignore
            .ftpconfig
